services:
  api:
    build: .
    container_name: auth_api_stg
    env_file:
      - .stg.env
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - stg_net

  postgres:
    image: postgres:17
    container_name: auth_postgres_stg
    environment:
      POSTGRES_DB: auth_stg_db
      POSTGRES_USER: stg_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_stg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stg_user -d auth_stg_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stg_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_stg
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
    networks:
      - stg_net

volumes:
  postgres_stg_data:

networks:
  stg_net:
